<?php

namespace Nerdroid23\BladeIcomoon;

use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;

class BladeIcomoonServiceProvider extends PackageServiceProvider
{
    public function configurePackage(Package $package): void
    {
        $package
            ->name('blade-icomoon')
            ->hasConfigFile();
    }

    public function registeringPackage()
    {
        parent::registeringPackage(); // TODO: Change the autogenerated stub
    }

    public function bootingPackage()
    {
        parent::bootingPackage(); // TODO: Change the autogenerated stub
    }
}
